### ISSUE TITLE
Cannot find module 'coffeelint-camel-case-vars'

### ISSUE THREAD

**Issue by KyleKing** [bsklaroff/coffeelint-camel-case-vars#8]
I'm trying to setup coffeelint-camel-case-vars, but I keep getting this error:

```
$ coffeelint client/t_admin/admin.coffee
Error: Cannot find module 'coffeelint-camel-case-vars' from '/Users/kyleking/Developer/TeamBikes/TeamBIKES/MeteorApp/client/t_admin'
  at module.exports (/usr/local/lib/node_modules/coffeelint/node_modules/resolve/lib/sync.js:32:11)
  at expandModuleNames (/usr/local/lib/node_modules/coffeelint/lib/configfinder.js:84:33)
  at Object.exports.getConfig (/usr/local/lib/node_modules/coffeelint/lib/configfinder.js:137:16)
  at getFallbackConfig (/usr/local/lib/node_modules/coffeelint/lib/commandline.js:140:27)
  at lintFiles (/usr/local/lib/node_modules/coffeelint/lib/commandline.js:95:38)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffeelint/lib/commandline.js:247:21)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffeelint/lib/commandline.js:252:4)
  at Module._compile (module.js:399:26)
  at Object.Module._extensions..js (module.js:406:10)
  at Module.load (module.js:345:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:355:17)
  at require (internal/module.js:13:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffeelint/bin/coffeelint:34:5)
  at Module._compile (module.js:399:26)
  at Object.Module._extensions..js (module.js:406:10)
  at Module.load (module.js:345:32)
  at Function.Module._load (module.js:302:12)
  at Function.Module.runMain (module.js:431:10)
  at startup (node.js:141:18)
  at node.js:977:3
```

Probably related, but originally I would get this error when installing:

```
$ npm i -g coffeelint-camel-case-vars
[cut]
/usr/local/lib
├── UNMET PEER DEPENDENCY coffeelint@^1.5
└── coffeelint-camel-case-vars@0.0.4

npm WARN coffeelint-camel-case-vars@0.0.4 requires a peer of coffeelint@^1.5 but none was installed.
```

Which I solved by running: `npm i -g coffeelint coffeelint-camel-case-vars`

I also checked:

```
$ echo $NODE_PATH
/usr/local/lib/node_modules/
```

I need to install everything globally for the coffeelint sublime linter. Do you know how I could solve this? Thanks in advance!

**Comment by KyleKing** [comment]
Weird, started working in sublime, but not on the command line? I am only interested in sublime, so this works for me
